### PR TITLE
Update dependencies to remove vulnerable package json-schema@0.2.3

### PR DESCRIPTION
**Pull request by Dinerville**
I updated node-pushnotifications and jest to remove vulnerable package json-schema@0.2.3

Could you merge it and release a new version please?

image

### CODE REVIEW

**Comment by BDav24** [comment]
Thanks for the PR.
There is a problem with jest version: https://github.com/notifme/notifme-sdk/actions/runs/8192007358/job/22441743362?pr=132

And there is also a problem with `push-notifications`: see https://github.com/notifme/notifme-sdk/pull/116
I think fixing this is more complex: transpilation and all dev tools need to be upgraded.

**Comment by Dinerville** [comment]
Thank you for reply
I'll have a look

**Comment by Dinerville** [comment]
@BDav24 I've update babel, tests passed locally, let me know if there are any issues

```
notifme-sdk % yarn test
yarn run v1.22.21
$ yarn run lint && yarn run testonly
$ yarn run flow && standard
$ /Users/dnaumau/Documents/Dinerville/notifme-sdk/node_modules/.bin/flow
No errors!
$ jest
 PASS  __tests__/strategies/providers/index.js
(node:16434) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 PASS  __tests__/providers/webpush/gcm.js
(node:16433) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 PASS  __tests__/providers/voice/twilio.js
(node:16432) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:16431) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 PASS  __tests__/providers/voice/index.js
 PASS  __tests__/providers/webpush/index.js
(node:16436) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 PASS  __tests__/providers/voice/notificationCatcher.js
(node:16435) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 PASS  __tests__/providers/webpush/notificationCatcher.js
(node:16437) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 PASS  __tests__/providers/sms/twilio.js
 PASS  __tests__/providers/email/sendgrid.js
 PASS  __tests__/providers/email/mailgun.js
 PASS  __tests__/providers/email/ses.js
 PASS  __tests__/providers/sms/notificationCatcher.js
 PASS  __tests__/providers/email/notificationCatcher.js
 PASS  __tests__/providers/slack/notificationCatcher.js
 PASS  __tests__/providers/slack/slack.js
 PASS  __tests__/providers/email/smtp.js
 PASS  __tests__/providers/sms/46elks.js
 PASS  __tests__/providers/email/sendmail.js
 PASS  __tests__/providers/email/mandrill.js
 PASS  __tests__/providers/email/index.js
 PASS  __tests__/providers/sms/callr.js
 PASS  __tests__/providers/slack/index.js
 PASS  __tests__/providers/sms/plivo.js
 PASS  __tests__/providers/sms/index.js
 PASS  __tests__/providers/sms/ovh.js
 PASS  __tests__/providers/sms/clickatell.js
 PASS  __tests__/providers/sms/nexmo.js
 PASS  __tests__/providers/email/sparkpost.js
 PASS  __tests__/strategies/providers/no-fallback.js
 PASS  __tests__/providers/sms/infobip.js
 PASS  __tests__/strategies/providers/fallback.js
 PASS  __tests__/strategies/providers/roundrobin.js
 PASS  __tests__/sender.js
 PASS  __tests__/providers/mockHttp.js
 PASS  __tests__/custom-channel.js
 PASS  __tests__/notifme-sdk.js

=============================== Coverage summary ===============================
Statements   : 100% ( 398/398 )
Branches     : 100% ( 311/311 )
Functions    : 100% ( 100/100 )
Lines        : 100% ( 365/365 )
================================================================================

Test Suites: 36 passed, 36 total
Tests:       121 passed, 121 total
Snapshots:   0 total
Time:        12.13 s
Ran all test suites.
✨  Done in 16.45s.
```

**Comment by BDav24** [comment]
Very nice, thanks!

**Pull request merged**
