### PR TITLE
Machine-In-The-Middle

### PR DESCRIPTION
**Pull request by udanpe**
https://www.npmjs.com/advisories/1184
Screenshot 2019-11-03 at 02 37 58

### CODE REVIEW

**Comment by 31453** [comment]
Can this get merged in?

**Comment by BDav24** [comment]
Would it be dangerous to upgrade strait to 5.0.0? I don't see any difference in their docs.

**Comment by 31453** [comment]
I don't think it would be dangerous because I don't see any breaking changes in their release notes either. As long as it gets tested, upgrading to v5 would be great.

**Comment by BDav24** [comment]
There you go: https://github.com/notifme/notifme-sdk/releases/tag/v1.9.3 :)

**Pull request closed without merging**
