### PR TITLE
added PLIVO as a SMS service provider

### PR DESCRIPTION
**Pull request by Abhishek-plivo**
Hey, this is Abhishek from Plivo . We saw this cool npm package and thought of adding Plivo as a SMS provider in this module . Please find the commit details mentioned below as well review the commits :- 

- [src/providers/sms/plivo.js](https://github.com/notifme/notifme-sdk/compare/master...plivo-dev:Add-Plivo-SMS-Provider?expand=1#diff-1c96dd72b8e20c435b6412f9b147de95) : added `SmsPlivoProvider` module for sending SMS via PLIVO
- [src/models/provider-sms.js](https://github.com/notifme/notifme-sdk/compare/master...plivo-dev:Add-Plivo-SMS-Provider?expand=1#diff-1a09658bbf25ea33eeadbdbd8d4a9500) : added plivo in sms-provider model
- [src/providers/sms/index.js](https://github.com/notifme/notifme-sdk/compare/master...plivo-dev:Add-Plivo-SMS-Provider?expand=1#diff-949038133c55af179460b3ca27a97102) : imported `SmsPlivoProvider` and enabled it to be used by giving `plivo` as the provider name 
- [README.md](https://github.com/notifme/notifme-sdk/compare/master...plivo-dev:Add-Plivo-SMS-Provider?expand=1#diff-04c6e90faac2675aa89e2176d2eec7d8) :  added documentation of initializing sdk with plivo.
- [.gitignore](https://github.com/notifme/notifme-sdk/compare/master...plivo-dev:Add-Plivo-SMS-Provider?expand=1#diff-a084b794bc0759e7a6b77810e01874f2) ignored automatically generated macbook files (`.DS_Store`)

### CODE REVIEW

**Comment by BDav24** [comment]
Hi @Abhishek-plivo thanks for your pull request!
We replaced `request` dependency by `node-fetch`, but don't worry I'll update your code.

**Comment by BDav24** [comment]
https://github.com/notifme/notifme-sdk/commit/67ea41be90afebf8443b685971bda06764c6c082

**Comment by Abhishek-plivo** [comment]
Thanks, @BDav24 .
I see Travis CI build failed . Does it need to change something in our commits  ?

**Comment by BDav24** [comment]
Everything's okay: https://travis-ci.org/notifme/notifme-sdk/builds/265611020 (I forgot to tag my commit with the reference of this PR, that's why it doesn't appear here)

**Comment by Abhishek-plivo** [comment]
cool , thanks

**Pull request merged**
