### PR TITLE
Introducing Whatsapp support

### PR DESCRIPTION
**Pull request by enricodeleo**
Introducing the first step towards the desire the community is sharing: whatsapp messages! 

I tried to follow conventions introducing this new channel and already implemented the first provider: **Infobip**. I could test only template messages but it should work for conversational messages too. Reference docs is here https://www.infobip.com/docs/api/channels/whatsapp/whatsapp-outbound-messages/send-whatsapp-template-message

Docs and example code are not ready yet, but help is welcomed.

### CODE REVIEW

**Comment by BDav24** [comment]
Thanks for the PR, I'll check it next week.

**Comment by BDav24** [comment]
@enricodeleo I added some tests, fixed linting, and also changed `WhatsappRequestType`, what do you think?

https://github.com/notifme/notifme-sdk/pull/166/files

**Comment by enricodeleo** [comment]
Looks great @BDav24 and shame on me I didn't do the job as good as you did, since the beginning! (In my defence it was the first time I contributed and had to learn hands-on the architecture of the library :))

**Comment by BDav24** [comment]
> Looks great @BDav24 and shame on me I didn't do the job as good as you did, since the beginning! (In my defence it was the first time I contributed and had to learn hands-on the architecture of the library :))

Not at all, you did well :+1:

**Comment by BDav24** [comment]
Closed in favor of https://github.com/notifme/notifme-sdk/pull/166

**Pull request closed without merging**
