### PR TITLE
Added Mandrill support

### PR DESCRIPTION
**Pull request by fluciotto**
Hi,

I just added Mandrill support through their API and the nodemailer-mandrill-transport module.

### CODE REVIEW

**Comment by BDav24** [comment]
Hi @fluciotto, thanks for the pull request!
I'm trying not to add too many dependencies (the goal would be to remove some), so would you like to try to call directly the mandrill api with http calls (with node-fetch)?

**Comment by fluciotto** [comment]
Hi,

Ok, i will update the pull request soon.

**Comment by fluciotto** [comment]
Hi @BDav24,

Did you check the PR update? What do you think about it?

**Comment by BDav24** [comment]
Ho you finished, I'll try to check it by the end of the week, thanks!

**Comment by BDav24** [comment]
Hi @fluciotto 
Still working on the review (https://github.com/notifme/notifme-sdk/commit/3b767664ff0d29288f509382c392c477aaef5f54), but the account I created to test was blocked because of "conflict with their Acceptable Use Policy "... I'll keep you posted.

**Comment by BDav24** [comment]
Hi @fluciotto sorry for the delay but they never unblocked my account :/
Anyway it's merged: https://github.com/notifme/notifme-sdk/releases/tag/v1.8.0

**Pull request merged**
